#cloud-config
autoinstall:
    version: 1
    identity:
        realname: CRC
        hostname: tiete
        username: crc
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - a2ps
        - alsa-ucm-conf
        - alsa-utils
        - apport
        - apport-gtk
        - apt
        - apt-transport-https
        - aptitude
        - asymptote
        - audacity
        - autoconf
        - autofs
        - autofs-ldap
        - autogen
        - automake
        - autopoint
        - base-passwd
        - biber
        - bison
        - build-essential
        - cabextract
        - clusterssh
        - cmake
        - codeblocks
        - colordiff
        - context
        - curl
        - cvs
        - dash
        - ddd
        - debhelper
        - diffutils
        - dirmngr
        - dkms
        - docker-compose
        - docker.io
        - fakeroot
        - fig2dev
        - findutils
        - finger
        - fingerd
        - firefox-locale-en
        - firefox-locale-pt
        - flex
        - fonts-dejavu
        - fonts-indic
        - fonts-liberation2
        - fonts-noto
        - fonts-noto-color-emoji
        - fonts-opensymbol
        - fping
        - friendly-recovery
        - g++
        - g++-9
        - gawk
        - gcc
        - gcc-9
        - gcc-multilib
        - gdbserver
        - gedit
        - genisoimage
        - gimp
        - git
        - gjs
        - glibc-doc
        - gnome-disk-utility
        - gnome-shell
        - gnome-shell-extension-appindicator
        - gnome-user-docs-pt
        - grep
        - grub-common
        - grub-gfxpayload-lists
        - grub-pc
        - grub-pc-bin
        - grub2-common
        - gsfonts
        - gv
        - gzip
        - hostname
        - htop
        - hyphen-en-us
        - hyphen-pt-br
        - iio-sensor-proxy
        - indicator-application
        - init
        - initramfs-tools
        - ipcalc
        - isc-dhcp-client
        - isc-dhcp-common
        - language-pack-en
        - language-pack-en-base
        - language-pack-gnome-en
        - language-pack-gnome-en-base
        - language-pack-gnome-pt
        - language-pack-gnome-pt-base
        - language-pack-pt
        - language-pack-pt-base
        - lib32ncurses6
        - liballegro-acodec5-dev
        - liballegro-dialog5-dev
        - liballegro-ttf5-dev
        - liballegro5-dev
        - libasound2t64
        - libatopology2t64
        - libdebconfclient0
        - libevent-pthreads-2.1-7t64
        - libexiv2-27
        - libfprint-2-tod1
        - libgjs0g
        - libgl1-mesa-dev
        - libgrpc++-dev
        - libgrpc29t64
        - libjpeg-dev
        - libjuh-java
        - libjurt-java
        - libldap-common
        - liblightdm-gobject-1-0
        - libnss-systemd
        - libpam-modules-bin
        - libpam-runtime
        - libpam0g
        - libpng-dev
        - libreoffice-base-core
        - libreoffice-help-common
        - libreoffice-help-en-us
        - libreoffice-help-pt
        - libreoffice-help-pt-br
        - libreoffice-l10n-pt
        - libreoffice-l10n-pt-br
        - libreoffice-impress
        - libreoffice-common
        - libreoffice-core
        - libreoffice-style-breeze
        - libreoffice-style-colibre
        - libreoffice-style-elementary
        - libreoffice-style-tango
        - libridl-java
        - libseccomp2
        - libssl-dev
        - libtool
        - libuno-cppu3t64
        - libuno-cppuhelpergcc3-3t64
        - libuno-purpenvhelpergcc3-3t64
        - libuno-sal3t64
        - libuno-salhelpergcc3-3t64
        - libunoloader-java
        - libwacom-bin
        - libwacom-common
        - libx11-dev
        - lightdm
        - linux-firmware
        - linux-headers-generic
        - magnus
        - make
        - manpages-posix-dev
        - mate-desktop-environment
        - meld
        - ml-lex
        - ml-yacc
        - mysql-client
        - mythes-en-us
        - nasm
        - ncurses-base
        - ncurses-bin
        - net-tools
        - openssh-server
        - os-prober
        - p7zip-full
        - p7zip-rar
        - php-cli
        - pkg-config
        - prerex
        - procmail
        - procps
        - pypy3
        - python3-dev
        - python3-distupgrade
        - python3-flask
        - python3-grpc-tools
        - python3-grpcio
        - python3-pip
        - python3-problem-report
        - python3-software-properties
        - python3-update-manager
        - python3-venv
        - python3-yaml
        - quota
        - rsync
        - ruby
        - smlnj
        - snmp
        - snmpd
        - sssd
        - subversion
        - synaptic
        - tcl
        - tcptraceroute
        - tcsh
        - texlive-full
        - thermald
        - thunderbird
        - thunderbird-locale-en
        - thunderbird-locale-en-us
        - thunderbird-locale-pt
        - thunderbird-locale-pt-br
        - tmux
        - traceroute
        - ubuntu-advantage-tools
        - ubuntu-desktop
        - ubuntu-desktop-minimal
        - ubuntu-keyring
        - ubuntu-mate-core
        - ubuntu-minimal
        - ubuntu-settings
        - ubuntu-standard
        - ubuntu-wallpapers
        - unrar
        - update-notifier
        - valgrind
        - vim
        - virtualenv
        - virtualenvwrapper
        - vlc
        - vprerex
        - wget
        - xfig
        - zlib1g-dev

    snaps:
        - name: audacity
        - name: thunderbird
        - name: code
          channel: stable
          classic: true
        - name: blender
          channel: stable
          classic: true
        - name: canonical-livepatch

    late-commands:
        - curtin in-target -- sudo apt-get update
        - curtin in-target -- sudo apt-get clean && sudo apt-get autoremove
        
        # 1. Instalar pacotes necessários para adicionar o repositório
        - curtin in-target -- sudo apt-get install -y wget gpg
        
        # 2. Adicionar a chave GPG do VirtualBox
        - curtin in-target -- sudo /bin/bash -c "wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | gpg --dearmor -o /usr/share/keyrings/oracle-virtualbox.gpg"
        
        # 3. Adicionar o repositório do VirtualBox (para Ubuntu 22.04/24.04)
        - curtin in-target -- sudo /bin/bash -c "echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox.gpg] https://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib' | tee /etc/apt/sources.list.d/virtualbox.list"
        
        # 4. Atualizar repositórios e instalar o VirtualBox
        - curtin in-target -- sudo apt-get update
        - curtin in-target -- sudo apt-get install -y virtualbox-7.0

        # 2. Criação da pasta de VMs
        - curtin in-target -- sudo mkdir -p /VirtualBox-VMs
        - curtin in-target -- sudo chmod 775 /VirtualBox-VMs
        
        # 3. Limpeza de pacotes desnecessários
        - curtin in-target -- sudo apt autoremove -y

    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot