#cloud-config
autoinstall:
    version: 1
    identity:
        realname: CRC
        hostname: tiete
        username: crc
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - git
        - vim
        - curl
        - gimp
        - htop
        - wget
        - xterm
        - docker.io
        - net-tools
        - codeblocks
        - clusterssh
        - virtualbox
        - python3-pip
        - libreoffice
        - docker-compose
        - build-essential
        - liballegro5-dev
    snaps:
        - name: audacity
        - name: code
          channel: stable
          classic: true
        - name: blender
          channel: stable
          classic: true
    late-commands:
        - sudo snap install audacity
        - sudo snap install code --classic 
        - sudo snap install blender --classic
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
