#cloud-config
autoinstall:
    version: 1
    identity:
        realname: CRC
        hostname: tiete
        username: crc
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - gv
        - git
        - vim
        - curl
        - a2ps
        - gimp
        - htop
        - wget
        - meld
        - tmux
        - acpi
        - caja
        - flex
        - acpid
        - biber
        - bison
        - plank
        - xterm
        - atril
        - gdebi
        - gedit
        - magnus
        - prerex
        - apturl
        - finger
        - feynmf
        - fig2dev
        - vprerex
        - blueman
        - autogen
        - gettext
        - grub-pc
        - gsfonts
        - autoconf
        - automake
        - aptitude
        - fakeroot
        - gdbserver
        - gdal-data
        - autopoint
        - asymptote
        - sharutils
        - docker.io
        - net-tools
        - glibc-doc
        - codeblocks
        - clusterssh
        - virtualbox
        - genisoimage
        - cpu-checker
        - libreoffice
        - thunderbird
        - python3-pip
        - python3-dev
        # - grpcio-tools
        - python3-venv
        - python3-grpcio
        - docker-compose
        - build-essential
        - liballegro5-dev
        - python3-pygments
        - python3-unittest2
        - python3-linecache2
        - python3-testresources
    snaps:
        - name: audacity
        - name: code
          channel: stable
          classic: true
        - name: blender
          channel: stable
          classic: true
    late-commands:
        - sudo snap install audacity
        - sudo snap install thunderbird
        - sudo snap install code --classic 
        - sudo snap install blender --classic
        - sudo snap install canonical-livepatch
        - mkdir /VirtualBox-VMs
        # - sudo chmod 777 /VistualBox-VMs
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
