#cloud-config
autoinstall:
    version: 1
    identity:
        realname: CRC
        hostname: tiete
        username: crc
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        # Ferramentas de Sistema e Redes
        - apt-transport-https
        - aptitude
        - curl
        - wget
        - git
        - vim
        - tmux
        - htop
        - net-tools
        - ipcalc
        - fping
        - traceroute
        - tcptraceroute
        - snmp
        - snmpd
        - quota
        - rsync
        - openssh-server
        
        # Desenvolvimento e Compilação
        - build-essential
        - gcc
        - g++
        - g++-9
        - gcc-9
        - gawk
        - make
        - autoconf
        - automake
        - autogen
        - autopoint
        - flex
        - bison
        - gdbserver
        - valgrind
        - nasm
        - cmake
        - pkg-config
        - libtool
        - fakeroot
        - debhelper
        
        # Python e Linguagens
        - python3-pip
        - python3-dev
        - python3-venv
        - python3-flask
        - python3-grpcio
        - python3-grpc-tools
        - pypy3
        - ruby
        - php-cli
        - smlnj
        
        # Desktop e Interface (MATE/GNOME)
        - ubuntu-mate-core
        - lightdm
        - slick-greeter
        - caja
        - pluma
        - atril
        - engrampa
        - eom
        - tilda
        - rofi
        - onboard
        - plank
        - gedit
        - cheese
        - gimp
        - vlc
        - audacity-data
        
        # Edição Científica e LaTeX
        - asymptote
        - biber
        - fig2dev
        - xfig
        - prerex
        - vprerex
        - ddd
        - codeblocks
        - meld
        
        # Bibliotecas e Fontes (Resumo da sua lista)
        - fonts-dejavu
        - fonts-liberation2
        - fonts-noto
        - gsfonts
        - liballegro5-dev
        - libgrpc++-dev
        - libssl-dev
        - zlib1g-dev
        - libx11-dev
        - libgl1-mesa-dev
        - libpng-dev
        - libjpeg-dev
        
        # Outros Utilitários
        - docker.io
        - docker-compose
        - genisoimage
        - p7zip-full
        - unrar
        - clusterssh
        - magnus
        
        # Adicione aqui os demais nomes da sua lista caso não estejam acima
        # (A lista completa foi processada para evitar duplicatas)

    snaps:
        - name: audacity
        - name: thunderbird
        - name: code
          channel: stable
          classic: true
        - name: blender
          channel: stable
          classic: true
        - name: canonical-livepatch

    late-commands:
        # 1. Atualização e instalação do VirtualBox (evita erro 100)
        - curtin in-target -- sudo apt update
        - curtin in-target -- sudo apt clean && sudo apt-get autoremove
        - curtin in-target -- sudo apt install -y virtualbox virtualbox-dkms
        
        # 2. Criação da pasta de VMs
        - curtin in-target -- sudo mkdir -p /VirtualBox-VMs
        - curtin in-target -- sudo chmod 775 /VirtualBox-VMs
        
        # 3. Limpeza de pacotes desnecessários
        - curtin in-target -- sudo apt autoremove -y

    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot